<?php
session_start();
$peeps = htmlspecialchars($_SESSION['word'][1]);
$name = htmlspecialchars($_SESSION['word'][2]);
$adj1 = htmlspecialchars($_SESSION['word'][3]);
$adj2 = htmlspecialchars($_SESSION['word'][4]);
$time = htmlspecialchars($_SESSION['word'][5]);
$timeinweeks = $time * 52;
$hometown = htmlspecialchars($_SESSION['word'][6]);
$verb1 = htmlspecialchars($_SESSION['word'][7]);
$verb2 = htmlspecialchars($_SESSION['word'][8]);
$verb3 = htmlspecialchars($_SESSION['word'][9]);
$favperson = htmlspecialchars($_SESSION['word'][10]);
$adj3 = htmlspecialchars($_SESSION['word'][11]);
$gender = htmlspecialchars($_SESSION['word'][12]);

include 'inc/header.php';

echo '<h1>My Rap</h1>';

echo '<p>Now listen up ' . $peeps;
echo ' I got the word <br>';
echo 'It\'s that ';
if ($gender == 'male') {
  echo 'rude dude ';
} else {
  echo 'cool chick ';
}
echo $name;
echo ' haven\'t you heard? <br>';
if ($gender == 'male') {
  echo 'He\'s ';
} else {
  echo 'She\'s ';
}
echo 'the ';
echo $adj1;
echo ', illest, take a look around<br>';
echo 'You won\'t find a ';
echo $adj2;
if ($gender == 'male') {
  echo ' guy ';
} else {
  echo ' girl ';
}
echo 'out there, that\'s the true sound.<br></p>';

echo '<p>My origin is deep, it\'s been ' . $timeinweeks . ' weeks <br>';
echo 'In the backstreets of ' . $hometown;
echo ', learnt to sneak <br>';
echo $verb1 . ', ' . $verb2 . ', ' . $verb3;
echo ', it\'s what I did <br>';
echo 'but now I\'m chilling with ' . $favperson;
echo ', no longer a kid. <br></p>';

echo 'My rap skills are pretty ' . $adj3 . ', huh?<br>';
echo 'promise it wasn\'t generated by a comput-erh<br>';
echo 'I hope this script ran smooth, without a bug<br>';
echo 'This is the end of the rap. Turn it off. Unplug.';
echo '<br></p>-';

echo ' <a class="btn btn-default btn-lg" href="inc/cookie.php?save" role="button">Save Story</a>';
echo ' <a class="btn btn-default btn-lg" href="play.php" role="button">Play Again</a>';
echo ' <a class="btn btn-default btn-lg" href="index.php" role="button">Other Stories</a>';


include 'inc/footer.php';
